# Generated by Django 3.2.8 on 2021-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('U_Name', models.CharField(max_length=100)),
                ('U_Email', models.CharField(max_length=100)),
                ('U_Created_On', models.DateField()),
                ('U_State', models.CharField(max_length=100)),
            ],
        ),
    ]
