# Generated by Django 3.2.8 on 2021-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='U_Created_On',
            field=models.CharField(max_length=100),
        ),
    ]
