# Generated by Django 3.2.8 on 2021-10-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_users_u_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='U_Name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='U_State',
        ),
        migrations.AddField(
            model_name='users',
            name='Addr_City',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Addr_State',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Addr_Zip',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Date_Of_Birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='F_Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='L_Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='M_Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Ph_Number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_Created_On',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_Email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
