# Generated by Django 3.2.8 on 2021-10-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20211014_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserId',
            field=models.IntegerField(default=int, max_length=3, primary_key=True, serialize=False),
        ),
    ]
