# Generated by Django 3.2.8 on 2021-10-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_users_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
