# Generated by Django 3.2.8 on 2021-10-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_users_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Addr_line_1',
            field=models.TextField(default=None, max_length=10000),
        ),
    ]
