# Generated by Django 3.2.8 on 2021-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20211020_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Note',
        ),
        migrations.AddField(
            model_name='users',
            name='Notes1',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
