# Generated by Django 3.2.8 on 2021-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_alter_users_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Date_Of_Birth',
            field=models.DateTimeField(),
        ),
    ]
