# Generated by Django 3.2.8 on 2021-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_users_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Addr_Zip',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='Addr_line_1',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_Email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
